package openfoodfacts.github.scrachx.openfood.features.product.edit.nutrition

import openfoodfacts.github.scrachx.openfood.features.shared.views.CustomValidatingEditTextView

fun getCompleteEntryName(editText: CustomValidatingEditTextView) =
        "$PREFIX_NUTRIMENT_LONG_NAME${editText.entryName.replace("_", "-")}"

fun getShortName(longName: String) = longName.removePrefix(PREFIX_NUTRIMENT_LONG_NAME)

const val PREFIX_NUTRIMENT_LONG_NAME = "nutriment_"

val PARAMS_OTHER_NUTRIENTS = listOf(
        PREFIX_NUTRIMENT_LONG_NAME + "alpha-linolenic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "arachidic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "arachidonic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "behenic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "bicarbonate",
        PREFIX_NUTRIMENT_LONG_NAME + "biotin",
        PREFIX_NUTRIMENT_LONG_NAME + "butyric-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "caffeine",
        PREFIX_NUTRIMENT_LONG_NAME + "calcium",
        PREFIX_NUTRIMENT_LONG_NAME + "capric-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "caproic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "caprylic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "casein",
        PREFIX_NUTRIMENT_LONG_NAME + "cerotic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "chloride",
        PREFIX_NUTRIMENT_LONG_NAME + "cholesterol",
        PREFIX_NUTRIMENT_LONG_NAME + "chromium",
        PREFIX_NUTRIMENT_LONG_NAME + "copper",
        PREFIX_NUTRIMENT_LONG_NAME + "dihomo-gamma-linolenic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "docosahexaenoic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "eicosapentaenoic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "elaidic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "erucic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "fluoride",
        PREFIX_NUTRIMENT_LONG_NAME + "fructose",
        PREFIX_NUTRIMENT_LONG_NAME + "gamma-linolenic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "glucose",
        PREFIX_NUTRIMENT_LONG_NAME + "gondoic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "iodine",
        PREFIX_NUTRIMENT_LONG_NAME + "iron",
        PREFIX_NUTRIMENT_LONG_NAME + "lactose",
        PREFIX_NUTRIMENT_LONG_NAME + "lauric-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "lignoceric-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "linoleic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "magnesium",
        PREFIX_NUTRIMENT_LONG_NAME + "maltodextrins",
        PREFIX_NUTRIMENT_LONG_NAME + "maltose",
        PREFIX_NUTRIMENT_LONG_NAME + "manganese",
        PREFIX_NUTRIMENT_LONG_NAME + "mead-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "melissic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "molybdenum",
        PREFIX_NUTRIMENT_LONG_NAME + "monounsaturated-fat",
        PREFIX_NUTRIMENT_LONG_NAME + "montanic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "myristic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "nervonic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "nucleotides",
        PREFIX_NUTRIMENT_LONG_NAME + "oleic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "omega-3-fat",
        PREFIX_NUTRIMENT_LONG_NAME + "omega-6-fat",
        PREFIX_NUTRIMENT_LONG_NAME + "omega-9-fat",
        PREFIX_NUTRIMENT_LONG_NAME + "palmitic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "pantothenic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "ph",
        PREFIX_NUTRIMENT_LONG_NAME + "phosphorus",
        PREFIX_NUTRIMENT_LONG_NAME + "polyols",
        PREFIX_NUTRIMENT_LONG_NAME + "polyunsaturated-fat",
        PREFIX_NUTRIMENT_LONG_NAME + "potassium",
        PREFIX_NUTRIMENT_LONG_NAME + "selenium",
        PREFIX_NUTRIMENT_LONG_NAME + "serum-proteins",
        PREFIX_NUTRIMENT_LONG_NAME + "silica",
        PREFIX_NUTRIMENT_LONG_NAME + "starch",
        PREFIX_NUTRIMENT_LONG_NAME + "stearic-acid",
        PREFIX_NUTRIMENT_LONG_NAME + "sucrose",
        PREFIX_NUTRIMENT_LONG_NAME + "taurine",
        PREFIX_NUTRIMENT_LONG_NAME + "trans-fat",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-a",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b1",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b12",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b2",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-pp",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b6",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b9",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-c",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-d",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-e",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-k",
        PREFIX_NUTRIMENT_LONG_NAME + "zinc"
)

val PARAMS_OTHER_NUTRIENTS_DEFAULT_UNITS = mapOf(
        PREFIX_NUTRIMENT_LONG_NAME + "alpha-linolenic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "arachidic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "arachidonic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "behenic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "bicarbonate" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "biotin" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "butyric-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "caffeine" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "calcium" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "capric-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "caproic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "caprylic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "casein" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "cerotic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "chloride" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "cholesterol" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "chromium" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "copper" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "dihomo-gamma-linolenic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "docosahexaenoic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "eicosapentaenoic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "elaidic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "erucic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "fluoride" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "fructose" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "gamma-linolenic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "glucose" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "gondoic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "iodine" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "iron" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "lactose" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "lauric-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "lignoceric-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "linoleic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "magnesium" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "maltodextrins" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "maltose" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "manganese" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "mead-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "melissic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "molybdenum" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "monounsaturated-fat" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "montanic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "myristic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "nervonic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "nucleotides" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "oleic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "omega-3-fat" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "omega-6-fat" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "omega-9-fat" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "palmitic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "pantothenic-acid" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "ph" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "phosphorus" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "polyols" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "polyunsaturated-fat" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "potassium" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "selenium" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "serum-proteins" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "silica" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "starch" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "stearic-acid" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "sucrose" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "taurine" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "trans-fat" to "g",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-a" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b1" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b12" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b2" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-pp" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b6" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-b9" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-c" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-d" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-e" to "mg",
        PREFIX_NUTRIMENT_LONG_NAME + "vitamin-k" to "µg",
        PREFIX_NUTRIMENT_LONG_NAME + "zinc" to "mg"
)