project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        zh-CN: zh-rCN
        en-AU: en-rAU
        en-GB: en-rGB
        nl-BE: nl-rBE
        nl: nl
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr-rRS # Serbian, Latin
        me: sr-rME
        sr: sr # Serbian, Cyrillic
        he: iw
        id: in
        yi: ji

  - source: /app/src/obf/res/values/strings.xml
    dest: /app/src/obf/res/values/strings.xml
    translation: /app/src/obf/res/values-%two_letters_code%/%original_file_name%
    preserve_hierarchy: true
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        zh-CN: zh-rCN
        en-AU: en-rAU
        en-GB: en-rGB
        nl-BE: nl-rBE
        nl: nl
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr-rRS # Serbian, Latin
        me: sr-rME
        sr: sr # Serbian, Cyrillic
        he: iw
        id: in
        yi: ji

  - source: /app/src/off/res/values/strings.xml
    dest: /app/src/off/res/values/strings.xml
    translation: /app/src/off/res/values-%two_letters_code%/%original_file_name%
    preserve_hierarchy: true
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        zh-CN: zh-rCN
        en-AU: en-rAU
        en-GB: en-rGB
        nl-BE: nl-rBE
        nl: nl
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr-rRS # Serbian, Latin
        me: sr-rME
        sr: sr # Serbian, Cyrillic
        he: iw
        id: in
        yi: ji

  - source: /app/src/opff/res/values/strings.xml
    dest: /app/src/opff/res/values/strings.xml
    translation: /app/src/opff/res/values-%two_letters_code%/strings.xml
    preserve_hierarchy: true
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        zh-CN: zh-rCN
        en-AU: en-rAU
        en-GB: en-rGB
        nl-BE: nl-rBE
        nl: nl
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr-rRS # Serbian, Latin
        me: sr-rME
        sr: sr # Serbian, Cyrillic
        he: iw
        id: in
        yi: ji

  - source: /app/src/opf/res/values/strings.xml
    dest: /app/src/opf/res/values/strings.xml
    translation: /app/src/opf/res/values-%two_letters_code%/strings.xml
    preserve_hierarchy: true
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        zh-CN: zh-rCN
        en-AU: en-rAU
        en-GB: en-rGB
        nl-BE: nl-rBE
        nl: nl
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr-rRS # Serbian, Latin
        me: sr-rME
        sr: sr # Serbian, Cyrillic
        he: iw
        id: in
        yi: ji
    
  - source: app/src/main/assets/changelog/changelog.json
    translation: app/src/main/assets/changelog/changelog-%locale%.json
    dest: app/src/main/assets/changelog/changelog.json
    preserve_hierarchy: true
    
  - source: app/src/off/assets/changelog/changelog.json
    translation: app/src/off/assets/changelog/changelog-%locale%.json
    dest: app/src/main/assets/changelog/changelog.json
    preserve_hierarchy: true
    
  - source: app/src/opff/assets/changelog/changelog.json
    translation: app/src/opff/assets/changelog/changelog-%locale%.json
    dest: app/src/main/assets/changelog/changelog.json
    preserve_hierarchy: true
    
  - source: app/src/opf/assets/changelog/changelog.json
    translation: app/src/opf/assets/changelog/changelog-%locale%.json
    dest: app/src/main/assets/changelog/changelog.json
    preserve_hierarchy: true
    
  - source: app/src/obf/assets/changelog/changelog.json
    translation: app/src/obf/assets/changelog/changelog-%locale%.json
    dest: app/src/main/assets/changelog/changelog.json
    preserve_hierarchy: true
