files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        zh-CN: zh-rCN
        en-AU: en-rAU
        en-GB: en-rGB
        nl-BE: nl-rBE
        nl: nl
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr
        sr: rs
        he: iw
        
  - source: /app/src/obf/res/values/strings.xml
    translation: /app/src/obf/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        en-GB: en-rGB
        pt-BR: pt-rBR
        en-AU: en-rAU
        pt-PT: pt-rPT
        nl-BE: nl-rBE
        nl: nl
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        sr-CS: sr
        sr: rs
        he: iw
        
  - source: /app/src/off/res/values/strings.xml
    translation: /app/src/off/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        en-GB: en-rGB
        en-AU: en-rAU
        nl-BE: nl-rBE
        pt-PT: pt-rPT
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        sr-CS: sr
        sr: rs
        he: iw
        
  - source: /app/src/opff/res/values/strings.xml
    translation: /app/src/opff/res/values-%two_letters_code%/strings.xml
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        en-GB: en-rGB
        en-AU: en-rAU
        pt-BR: pt-rBR
        nl-BE: nl-rBE
        pt-PT: pt-rPT
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr
        sr: rs
        he: iw

  - source: /app/src/opf/res/values/strings.xml
    translation: /app/src/opf/res/values-%two_letters_code%/strings.xml
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        en-GB: en-rGB
        en-AU: en-rAU
        pt-BR: pt-rBR
        nl-BE: nl-rBE
        pt-PT: pt-rPT
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr
        sr: rs
        he: iw

  - source: /fastlane/metadata/android/en-US/off/long_description.txt
    translation: /fastlane/metadata/android/%locale%/off/long_description.txt

  - source: /fastlane/metadata/android/en-US/obf/long_description.txt
    translation: /fastlane/metadata/android/%locale%/obf/long_description.txt

  - source: /fastlane/metadata/android/en-US/opff/long_description.txt
    translation: /fastlane/metadata/android/%locale%/opff/long_description.txt
        
  - source: /fastlane/metadata/android/en-US/opf/long_description.txt
    translation: /fastlane/metadata/android/%locale%/opf/long_description.txt

  - source: /fastlane/metadata/android/en-US/off/short_description.txt
    translation: /fastlane/metadata/android/%locale%/off/short_description.txt
        
  - source: /fastlane/metadata/android/en-US/obf/short_description.txt
    translation: /fastlane/metadata/android/%locale%/obf/short_description.txt
    
  - source: /fastlane/metadata/android/en-US/opff/short_description.txt
    translation: /fastlane/metadata/android/%locale%/opff/short_description.txt
        
  - source: /fastlane/metadata/android/en-US/opf/short_description.txt
    translation: /fastlane/metadata/android/%locale%/opf/short_description.txt
        
  - source: /fastlane/metadata/android/en-US/off/title.txt
    translation: /fastlane/metadata/android/%locale%/off/title.txt
    
  - source: /fastlane/metadata/android/en-US/off/changelog.txt
    translation: /fastlane/metadata/android/%locale%/off/changelog.txt
 
  - source: /fastlane/metadata/android/en-US/off/changelog-light.txt
    translation: /fastlane/metadata/android/%locale%/off/changelog-light.txt

  - source: /fastlane/metadata/android/en-US/obf/title.txt
    translation: /fastlane/metadata/android/%locale%/obf/title.txt

  - source: /fastlane/metadata/android/en-US/opff/title.txt
    translation: /fastlane/metadata/android/%locale%/opff/title.txt
        
  - source: /fastlane/metadata/android/en-US/opf/title.txt
    translation: /fastlane/metadata/android/%locale%/opf/title.txt

  - source: /fastlane/metadata/android/en-US/off/screenshot-text.txt
    translation: /fastlane/metadata/android/%locale%/off/screenshot-text.txt

  - source: /fastlane/metadata/android/en-US/off/novagroups.txt
    translation: /fastlane/metadata/android/%locale%/off/novagroups.txt
