name: Bug Report (Guided)
description: File a guided bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Open Food Facts username
      description: to get in touch with you if we need more info
      placeholder: ex. teolemon
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? (Open the left menu, scroll down to Settings, and scroll down to the bottom of settings to get it)
      options:
        - 3.6.5 (Default)
        - 3.6.6 (Beta)
    validations:
      required: true
  - type: dropdown
    id: flavor
    attributes:
      label: Flavor
      description: Were you running Open Food Facts, Open Beauty Facts, Open Pet Food Facts or Open Products Facts?
      options:
        - Open Food Facts
        - Open Beauty Facts
        - Open Pet Food Facts
        - Open Products Facts
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
