name: Google Play internal release

on:
  push:
    branches:
      - 'release/*'

jobs:

  testOff:
    name: Test OFF
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Unit tests
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: testOffPlaystoreDebugUnitTest --stacktrace

  testObf:
    name: Test OBF
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Unit tests
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: testObfPlaystoreDebugUnitTest --stacktrace

  testOpf:
    name: Test OPF
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Unit tests
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: testOpfPlaystoreDebugUnitTest --stacktrace

  testOpff:
    name: Test OPFF
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Unit tests
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: testOpffPlaystoreDebugUnitTest --stacktrace

  google-play-internal:
    name: Deploy OFF on Google Play
    runs-on: ubuntu-20.04

    needs:
      - testObf
      - testOff
      - testOpf
      - testOpff

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Decrypt api json file
        run: cd ./fastlane/envfiles && ./decrypt_secrets.sh
        env:
          API_JSON_FILE_DECRYPTKEY: ${{ secrets.API_JSON_FILE_DECRYPTKEY }}
          STORE_JKS_DECRYPTKEY: ${{ secrets.STORE_JKS_DECRYPTKEY }}
          OBF_STORE_JKS_DECRYPTKEY: ${{ secrets.OBF_STORE_JKS_DECRYPTKEY }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Workaround for Android Gradle Plugin issue
        run: "echo \"ndk.dir=${ANDROID_HOME}/ndk-bundle\" > local.properties"

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.1
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install sentry-cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Run Fastlane release lane for Open Food Facts
        run: bundle exec fastlane release-to-org-openfoodfacts-app
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CI_RELEASE: true
          SIGN_STORE_PATH: ../fastlane/envfiles/keystore.jks
          SIGN_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
          SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}

      - name: Run Fastlane release lane for Open Products Facts
        run: bundle exec fastlane release_opf
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CI_RELEASE: true
          SIGN_STORE_PATH: ../fastlane/envfiles/keystore.jks
          SIGN_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
          SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
          PACKAGE_NAME: "org.openproductsfacts.scanner"

      - name: Run Fastlane release lane for Open Pet Food Facts
        run: bundle exec fastlane release_opff
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CI_RELEASE: true
          SIGN_STORE_PATH: ../fastlane/envfiles/OpenBeautyFactsProd.key
          SIGN_STORE_PASSWORD: ${{ secrets.OBF_SIGN_STORE_PASSWORD }}
          SIGN_KEY_ALIAS: ${{ secrets.OBF_SIGN_KEY_ALIAS }}
          SIGN_KEY_PASSWORD: ${{ secrets.OBF_SIGN_KEY_PASSWORD }}
          PACKAGE_NAME: "org.openpetfoodfacts.scanner"
          
      - name: Run Fastlane release lane for Open Beauty Facts
        run: bundle exec fastlane release_obf
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CI_RELEASE: true
          SIGN_STORE_PATH: ../fastlane/envfiles/OpenBeautyFactsProd.key
          SIGN_STORE_PASSWORD: ${{ secrets.OBF_SIGN_STORE_PASSWORD }}
          SIGN_KEY_ALIAS: ${{ secrets.OBF_SIGN_KEY_ALIAS }}
          SIGN_KEY_PASSWORD: ${{ secrets.OBF_SIGN_KEY_PASSWORD }}
          PACKAGE_NAME: "org.openbeautyfacts.scanner"
