name: Release Please
on:
  push:
    branches:
      - develop

jobs:
  release-please:
    name: Update release PR
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple